"""
Markov Noise Generator
======================
Purpose:
    Generate synthetic token sequences with configurable n-gram memory. Used as
    the floor null model in the retrodiction pipeline.

    The Markov null model establishes the minimum expected score: any linguistically
    valid reconstruction must score significantly above a sequence generated by
    random n-gram sampling with no underlying grammar or semantics.

Null model design:
    Two modes are supported:

    UNIFORM mode (default): transition probabilities are uniform across the
    vocabulary. Each generated token is drawn uniformly at random from the
    vocabulary regardless of context. This produces sequences with no
    statistical structure beyond vocabulary distribution. For n=1 (unigram),
    this is equivalent to sampling from the vocabulary with replacement.
    For n>1, context does not affect the transition — uniform transitions at
    every step regardless of n.

    TRAINED mode: transition probabilities are estimated from a seed corpus.
    The resulting sequences have n-gram statistics that resemble the seed but
    with no higher-order structure. This is a stronger null model — it tests
    whether the reconstruction captures something beyond mere n-gram frequency.

    For Phase 2, UNIFORM mode at n=2 is the primary null model. TRAINED mode
    is available for sensitivity analysis.

    Decision log: docs/decisions/007_markov_null_model.md

Output format:
    The generator produces token sequences in the same format as the tokenized
    corpora — a list of token lists. These are passed directly to the fingerprint
    builders to produce a Markov noise fingerprint.

    The generated fingerprint is saved to data/processed/nulls/markov/.

Parameters:
    n (int, default=2): n-gram order. n=1 = unigram, n=2 = bigram.
    vocab_size (int, default=500): vocabulary size for uniform mode.
    seq_length (int, default=10): tokens per generated sequence.
    num_sequences (int, default=10000): number of sequences to generate.

    Decision log: docs/decisions/007_markov_null_model.md

Assumptions:
    - In UNIFORM mode, the vocabulary is a set of integer strings ("0", "1", ...,
      "N-1") representing abstract token IDs. The specific symbols don't matter —
      only their statistical behavior is relevant.
    - Sequence length is fixed for simplicity. Real corpora have variable length;
      this is flagged in the metadata.

Known limitations:
    - Fixed sequence length is an approximation. Real corpus sequences vary in
      length; this introduces a small bias in positional statistics. Since the
      null model is a floor (not a target), this is acceptable.
    - UNIFORM mode with large vocabularies generates very sparse co-occurrence
      matrices. This is expected and reflects the absence of linguistic structure.

Validation:
    - Generated sequences must have the specified length.
    - Vocabulary must contain the expected number of types.
    - Type/token ratio should be close to vocab_size / (num_sequences * seq_length)
      for uniform mode.

Usage:
    python -m src.nullmodel.markov
    python -m src.nullmodel.markov --n 1 --vocab-size 1000 --num-sequences 20000
"""

import argparse
import json
import logging
from collections import defaultdict
from pathlib import Path

import numpy as np

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]
NULLS_DIR = PROJECT_ROOT / "data" / "processed" / "nulls" / "markov"

# ---------------------------------------------------------------------------
# Default parameters
# ---------------------------------------------------------------------------

DEFAULT_N = 2
DEFAULT_VOCAB_SIZE = 500
DEFAULT_SEQ_LENGTH = 10
DEFAULT_NUM_SEQUENCES = 10_000

# ---------------------------------------------------------------------------
# Uniform Markov generator
# ---------------------------------------------------------------------------

def generate_uniform(
    vocab_size: int,
    seq_length: int,
    num_sequences: int,
    n: int,
    seed: int | None = None,
) -> list[list[str]]:
    """
    Generate sequences with uniform token transitions (no linguistic structure).

    In uniform mode, the n-gram order n has no effect on output statistics —
    transitions are always uniform regardless of context. The parameter n is
    recorded in metadata for documentation purposes.

    Args:
        vocab_size:     Number of distinct token types.
        seq_length:     Fixed number of tokens per sequence.
        num_sequences:  Number of sequences to generate.
        n:              N-gram order (recorded in metadata; does not affect
                        uniform generation).
        seed:           Random seed for reproducibility.

    Returns:
        List of token sequences.
    """
    rng = np.random.default_rng(seed)
    vocab = [str(i) for i in range(vocab_size)]
    sequences = [
        [vocab[int(rng.integers(0, vocab_size))] for _ in range(seq_length)]
        for _ in range(num_sequences)
    ]
    return sequences


# ---------------------------------------------------------------------------
# Trained Markov generator
# ---------------------------------------------------------------------------

def build_transitions(
    sequences: list[list[str]],
    n: int,
) -> dict[tuple[str, ...], list[str]]:
    """
    Build n-gram transition table from a seed corpus.

    For each (n-1)-gram context observed in the corpus, record all tokens
    that follow it. Transitions are stored as lists (with repetition) to
    enable weighted sampling by frequency.

    Returns:
        transitions: {context_tuple: [next_token, ...]}
    """
    transitions: dict[tuple[str, ...], list[str]] = defaultdict(list)
    for seq in sequences:
        for i in range(len(seq) - n + 1):
            context = tuple(seq[i : i + n - 1])
            next_tok = seq[i + n - 1]
            transitions[context].append(next_tok)
    return dict(transitions)


def generate_trained(
    seed_sequences: list[list[str]],
    seq_length: int,
    num_sequences: int,
    n: int,
    random_seed: int | None = None,
) -> list[list[str]]:
    """
    Generate sequences whose n-gram statistics match a seed corpus.

    At each step, the last (n-1) tokens form the context. The next token
    is sampled uniformly from all tokens that followed that context in the
    seed corpus. If the context has never been seen (sparse coverage), fall
    back to a random token from the full vocabulary.

    Args:
        seed_sequences: The training corpus.
        seq_length:     Fixed tokens per generated sequence.
        num_sequences:  Number of sequences to generate.
        n:              N-gram order.
        random_seed:    Random seed for reproducibility.

    Returns:
        List of token sequences.
    """
    rng = np.random.default_rng(random_seed)
    transitions = build_transitions(seed_sequences, n)

    # Build flat vocabulary for fallback sampling.
    vocab: list[str] = []
    for seq in seed_sequences:
        vocab.extend(seq)
    unique_vocab = list(set(vocab))
    context_keys = list(transitions.keys())

    sequences: list[list[str]] = []
    for _ in range(num_sequences):
        # Seed the sequence with a random (n-1)-gram context from training data.
        if context_keys:
            context = context_keys[int(rng.integers(0, len(context_keys)))]
            seq = list(context)
        else:
            seq = [unique_vocab[int(rng.integers(0, len(unique_vocab)))] for _ in range(max(1, n - 1))]

        while len(seq) < seq_length:
            context = tuple(seq[-(n - 1):]) if n > 1 else ()
            candidates = transitions.get(context, unique_vocab)
            seq.append(candidates[int(rng.integers(0, len(candidates)))])

        sequences.append(seq[:seq_length])

    return sequences


# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------

def write_output(
    sequences: list[list[str]],
    params: dict,
    output_dir: Path = NULLS_DIR,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)

    total_tokens = sum(len(s) for s in sequences)
    types = set(tok for seq in sequences for tok in seq)

    corpus = {
        "language": "markov_null",
        "source": "generated",
        "mode": params.get("mode", "uniform"),
        "n": params.get("n", DEFAULT_N),
        "vocab_size": len(types),
        "seq_length": params.get("seq_length", DEFAULT_SEQ_LENGTH),
        "num_sequences": len(sequences),
        "total_tokens": total_tokens,
        "type_token_ratio": len(types) / total_tokens if total_tokens > 0 else 0.0,
        "random_seed": params.get("seed"),
        "sequences": sequences,
    }

    tokens_path = output_dir / "markov_tokens.json"
    with tokens_path.open("w", encoding="utf-8") as fh:
        json.dump(corpus, fh, ensure_ascii=False, indent=2)
    log.info(
        "Wrote Markov null corpus: n=%d, vocab=%d, sequences=%d, tokens=%d → %s",
        params.get("n", DEFAULT_N),
        len(types),
        len(sequences),
        total_tokens,
        tokens_path,
    )
    return tokens_path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run(
    n: int = DEFAULT_N,
    vocab_size: int = DEFAULT_VOCAB_SIZE,
    seq_length: int = DEFAULT_SEQ_LENGTH,
    num_sequences: int = DEFAULT_NUM_SEQUENCES,
    seed: int | None = 42,
    output_dir: Path = NULLS_DIR,
) -> list[list[str]]:
    """
    Generate a Markov noise corpus and write it to disk.

    Args:
        n:             N-gram order (default 2; see decision log 007).
        vocab_size:    Vocabulary size for uniform generation.
        seq_length:    Tokens per sequence.
        num_sequences: Number of sequences to generate.
        seed:          Random seed (default 42 for reproducibility).
        output_dir:    Output directory.

    Returns:
        The generated sequences.
    """
    log.info(
        "Generating Markov null corpus: n=%d, vocab_size=%d, seq_length=%d, "
        "num_sequences=%d, seed=%s",
        n, vocab_size, seq_length, num_sequences, seed,
    )
    sequences = generate_uniform(vocab_size, seq_length, num_sequences, n, seed)

    params = {
        "mode": "uniform",
        "n": n,
        "vocab_size": vocab_size,
        "seq_length": seq_length,
        "num_sequences": num_sequences,
        "seed": seed,
    }
    write_output(sequences, params, output_dir)
    return sequences


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Markov noise null corpus")
    parser.add_argument("--n", type=int, default=DEFAULT_N, help="N-gram order")
    parser.add_argument("--vocab-size", type=int, default=DEFAULT_VOCAB_SIZE)
    parser.add_argument("--seq-length", type=int, default=DEFAULT_SEQ_LENGTH)
    parser.add_argument("--num-sequences", type=int, default=DEFAULT_NUM_SEQUENCES)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    run(
        n=args.n,
        vocab_size=args.vocab_size,
        seq_length=args.seq_length,
        num_sequences=args.num_sequences,
        seed=args.seed,
    )
